services:
    laravel:
        restart: unless-stopped
        container_name: ${APP_NAME}
        build:
            context: ../
            dockerfile: ./deploy/Dockerfile
        # allocate as many volumes as necessary, if needed.
        volumes:
            - ../storage/app:/var/www/html/storage/app
        ports:
            - "8080:80"
        networks:
            - n-laravel

networks:
    n-laravel:
        driver: bridge
